control_variables: #tag: [device_name, variable_name, min_value, max_value]
  JetX: 
    device_name: U_ESP_JetXYZ
    device_variable: Position.Axis 1
    range: [ 2.0, 7.0]
    ipaddress: 0.0.0.0
    port: 9999
    busy: 0
    newDataFlag: 0
    tcp_client: 'na'
    actual_value: 0.0
    set: True
    set_value: 0.0
    proximal_lengthscale: 1.5
    objective: False
  JetY:
    device_name: U_ESP_JetXYZ
    device_variable: Position.Axis 2
    range: [ -8.0, -5.0]
    ipaddress: 0.0.0.0
    port: 9999
    busy: 0
    newDataFlag: 0
    tcp_client: 'na'
    actual_value: 0.0
    set: True
    set_value: 0.0
    proximal_lengthscale: 1.5
    objective: False
