control_variables: #tag: [device_name, variable_name, min_value, max_value]
  ExposureM1: 
    device_name: CAM-1BL-M1
    device_variable: exposure
    range: [ 0.001, 0.2]
    ipaddress: 0.0.0.0
    port: 9999
    busy: 0
    newDataFlag: 0
    tcp_client: 'na'
    actual_value: 0.0
    set: True
    set_value: 0.0
    proximal_lengthscale: 1.5
    objective: False
  GainM1: 
    device_name: CAM-1BL-M1
    device_variable: gain
    range: [ 220, 400]
    ipaddress: 0.0.0.0
    port: 9999
    busy: 0
    newDataFlag: 0
    tcp_client: 'na'
    actual_value: 0.0
    set: True
    set_value: 0.0
    proximal_lengthscale: 100
    objective: False
  Charge: 
    device_name: CAM-1BL-M1
    device_variable: MeanCounts
    ipaddress: 0.0.0.0
    port: 9999
    busy: 0
    newDataFlag: 0
    tcp_client: 'na'
    actual_value: 0.0
    method: 'MAXIMIZE'
    objective: True
    set: False
database:
  name: loasis
  port: 3306
  ipaddress: 192.168.13.23
  user: loasis
  password: dat+l0sim
optimization_parameters:
  shots_per_step: 2