"""External asset spec names and supported GEECS device types."""

GEECS_CAMERA_IMAGE = "GEECS_CAMERA_IMAGE"
GEECS_TDMS_FILE = "GEECS_TDMS_FILE"
GEECS_TEXT_ARRAY = "GEECS_TEXT_ARRAY"

FROG_DEVICE_TYPE = "FROG"
MAGSPEC_CAMERA_DEVICE_TYPE = "MagSpecCamera"
MAGSPEC_STITCHER_DEVICE_TYPE = "MagSpecStitcher"
PICOSCOPE_V2_DEVICE_TYPE = "PicoscopeV2"
POINTGREY_CAMERA_DEVICE_TYPE = "Point Grey Camera"
ROHDE_SCHWARZ_RTA4000_DEVICE_TYPE = "RohdeSchwarz_RTA4000"
THORLABS_CCS175_SPECTROMETER_DEVICE_TYPE = "Thorlabs CCS175 Spectrometer"
THORLABS_WFS_DEVICE_TYPE = "ThorlabsWFS"
