Station1:
  Background Level: 1
  Left ROI: 1
  Size_X: 500
  Top ROI: 1
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 1
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 0

Station2:
  Background Level: 0.25
  Left ROI: 1930
  Size_X: 500
  Top ROI: 450
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 3
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station3:
  Background Level: 0
  Left ROI: 1300
  Size_X: 500
  Top ROI: 830
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 5
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station4:
  Background Level: 0
  Left ROI: 2010
  Size_X: 500
  Top ROI: 570
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 3
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station5:
  Background Level: 0
  Left ROI: 1430
  Size_X: 500
  Top ROI: 600
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 3
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station6:
  Background Level: 0
  Left ROI: 1450
  Size_X: 500
  Top ROI: 220
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 3
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station7:
  Background Level: 0
  Left ROI: 1880
  Size_X: 500
  Top ROI: 850
  Size_Y: 400
  Median Filter Size: 5
  Median Filter Cycles: 3
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 1

Station8:
  Background Level: 1
  Left ROI: 1500
  Size_X: 500
  Top ROI: 1
  Size_Y: 400
  Median Filter Size: 3
  Median Filter Cycles: 1
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 0


Station9:
  Background Level: 1
  Left ROI: 1600
  Size_X: 500
  Top ROI: 650
  Size_Y: 400
  Median Filter Size: 3
  Median Filter Cycles: 1
  Gaussian Filter Size: 3
  Gaussian Filter Cycles: 0





