repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "(^extras/|.*/third_party_sdks/)"
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        exclude: "(^extras/|.*/third_party_sdks/)"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
        exclude: "(^extras/|.*/third_party_sdks/)"
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        exclude: "(^extras/|.*/third_party_sdks/)"

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [tomli]
        args: [--convention=numpy, --add-ignore=D401,D200,D400]
        exclude: "(^extras/|.*/third_party_sdks/)"

  - repo: local
    hooks:
      - id: jupyter-notebook-clear-output
        name: jupyter-notebook-jupyter-clear
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        exclude: '(^extras/|.*/third_party_sdks/).*\.ipynb$'
