# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        exclude: "^(python/versioneer.py|python/xopt/_version.py)$"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=numpy, --add-ignore=D401,D200,D400]
        exclude: |
          (?x)^(
              .*/__pycache__/.*|
              .*/tests/.*|
              .*/test_.*\.py|
              .*_test\.py|
              .*/conftest\.py|
              .*/setup\.py|
              .*/versioneer\.py|
              .*/_version\.py|
              .*/PW_scripts/.*|
              .*/khzwave_python-master/.*|
              .*third_party_sdks/.*|
              .*tcp client/.*|
              .*Xopt-GEECS/.*|
              .*Spot Alignment for HDR Profile/.*|
              .*openPMD-CCD/.*|
              .*LogMaker.*/.*|
              .*LivePostProcessing/.*
          )$

  - repo: local
    hooks:
      - id: jupyter-notebook-clear-output
        name: jupyter-notebook-jupyter-clear
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        exclude: "^.*(TODO|TODO2).ipynb$"
