version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: GEECS-Scanner-GUI
    - method: pip
      path: ImageAnalysis
    - requirements: docs/requirements.txt
