# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml  # or makedocs.yml if that's your file

python:
  install:
    - method: pip
      path: .