# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(20, 310, 93, 28))
        self.buttonStart.setObjectName("buttonStart")
        self.buttonStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStop.setGeometry(QtCore.QRect(130, 310, 93, 28))
        self.buttonStop.setObjectName("buttonStop")
        self.inputYear = QtWidgets.QLineEdit(self.centralwidget)
        self.inputYear.setGeometry(QtCore.QRect(90, 50, 113, 22))
        self.inputYear.setObjectName("inputYear")
        self.inputMonth = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMonth.setGeometry(QtCore.QRect(90, 80, 113, 22))
        self.inputMonth.setObjectName("inputMonth")
        self.inputDay = QtWidgets.QLineEdit(self.centralwidget)
        self.inputDay.setGeometry(QtCore.QRect(90, 110, 113, 22))
        self.inputDay.setObjectName("inputDay")
        self.labelYear = QtWidgets.QLabel(self.centralwidget)
        self.labelYear.setGeometry(QtCore.QRect(40, 50, 31, 21))
        self.labelYear.setObjectName("labelYear")
        self.labelMonth = QtWidgets.QLabel(self.centralwidget)
        self.labelMonth.setGeometry(QtCore.QRect(40, 80, 41, 21))
        self.labelMonth.setObjectName("labelMonth")
        self.labelDay = QtWidgets.QLabel(self.centralwidget)
        self.labelDay.setGeometry(QtCore.QRect(40, 110, 41, 21))
        self.labelDay.setObjectName("labelDay")
        self.logDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.logDisplay.setGeometry(QtCore.QRect(240, 40, 631, 311))
        self.logDisplay.setObjectName("logDisplay")
        self.inputStartScan = QtWidgets.QLineEdit(self.centralwidget)
        self.inputStartScan.setGeometry(QtCore.QRect(90, 220, 113, 22))
        self.inputStartScan.setObjectName("inputStartScan")
        self.labelStartScan = QtWidgets.QLabel(self.centralwidget)
        self.labelStartScan.setGeometry(QtCore.QRect(20, 220, 61, 21))
        self.labelStartScan.setObjectName("labelStartScan")
        self.labelIgnore = QtWidgets.QLabel(self.centralwidget)
        self.labelIgnore.setGeometry(QtCore.QRect(10, 250, 81, 21))
        self.labelIgnore.setObjectName("labelIgnore")
        self.inputIgnore = QtWidgets.QLineEdit(self.centralwidget)
        self.inputIgnore.setGeometry(QtCore.QRect(90, 250, 113, 22))
        self.inputIgnore.setObjectName("inputIgnore")
        self.labelScanSettings = QtWidgets.QLabel(self.centralwidget)
        self.labelScanSettings.setGeometry(QtCore.QRect(70, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelScanSettings.setFont(font)
        self.labelScanSettings.setObjectName("labelScanSettings")
        self.buttonOverwrite = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOverwrite.setGeometry(QtCore.QRect(50, 180, 131, 31))
        self.buttonOverwrite.setObjectName("buttonOverwrite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.labelYear.setText(_translate("MainWindow", "Year"))
        self.labelMonth.setText(_translate("MainWindow", "Month"))
        self.labelDay.setText(_translate("MainWindow", "Day"))
        self.labelStartScan.setText(_translate("MainWindow", "Start Scan"))
        self.labelIgnore.setText(_translate("MainWindow", "Ignore Scans"))
        self.labelScanSettings.setText(_translate("MainWindow", "Scan Settings"))
        self.buttonOverwrite.setText(_translate("MainWindow", "Overwrite Processed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
