"""Generate the Phoebus fleet screen for one experiment from the DB roster.

Usage (on the lab network — it queries the GEECS DB)::

    python gen_fleet_status.py                     # experiment from config.ini
    python gen_fleet_status.py --experiment HTU    # writes fleet_status_htu.bob

One row per camera server in :func:`geecs_pva_gateway.fleet.fleet_roster`:
endpoint IPs hosting the experiment's enabled image devices. Hosts in the
client ``config.ini`` ``[pva] addr_list`` get live version/heartbeat cells
and a restart button; roster hosts absent from that list render as **not
deployed** (no instance was installed there — cameras only nominally) with
no live PVs. Regenerate and commit the ``.bob`` when the fleet changes
(a box added or retired, an instance installed). The committed
``fleet_status_undulator.bob`` is HTU's, the reference deployment.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from xml.sax.saxutils import escape

from geecs_core.pv_naming import normalize_component
from geecs_pva_gateway.fleet import FleetHost, default_experiment, fleet_roster

ROW_HEIGHT = 30
FIRST_ROW_Y = 95

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Fleet health for GeecsPvaGateway instances: one row per camera server.
     GENERATED by gen_fleet_status.py from the GEECS DB roster (endpoints
     hosting image devices) + config.ini [pva] addr_list (deployed hosts) -
     rerun that script, do not hand-edit rows.
     Rollout = write 1 to :restart (confirmation dialog) - the service
     relaunches and reinstalls from the source clone; watch version converge.
     NOTE: this screen is itself a cross-subnet PVA client - Phoebus needs
     the full fleet address list (DEPLOYMENT.md "Client access") or rows on
     other subnets show disconnected. -->
<display version="2.0.0">
  <name>PVA Gateway Fleet</name>
  <width>640</width>
  <height>{height}</height>
  <widget type="label" version="2.0.0">
    <name>title</name>
    <text>GeecsPvaGateway fleet — {experiment}</text>
    <x>10</x><y>10</y><width>400</width><height>25</height>
    <font><font family="Liberation Sans" style="BOLD" size="16.0"></font></font>
  </widget>
  <widget type="label" version="2.0.0">
    <name>subtitle</name>
    <text>{n_hosts} camera servers in the DB, {n_deployed} deployed (config.ini [pva] addr_list)</text>
    <x>10</x><y>40</y><width>600</width><height>20</height>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_host</name>
    <text>host</text>
    <x>10</x><y>70</y><width>150</width><height>20</height>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_version</name>
    <text>version</text>
    <x>170</x><y>70</y><width>150</width><height>20</height>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_heartbeat</name>
    <text>heartbeat</text>
    <x>330</x><y>70</y><width>100</width><height>20</height>
  </widget>
"""

HOST_LABEL = """
  <!-- row: {ip} ({n_cameras} cameras) -->
  <widget type="label" version="2.0.0">
    <name>host_{suffix}</name>
    <text>{ip}</text>
    <x>10</x><y>{y}</y><width>150</width><height>20</height>
    <tooltip>{cameras}</tooltip>
  </widget>
"""

DEPLOYED_CELLS = """
  <widget type="textupdate" version="2.0.0">
    <name>version_{suffix}</name>
    <pv_name>pva://{version_pv}</pv_name>
    <x>170</x><y>{y}</y><width>150</width><height>20</height>
  </widget>
  <widget type="textupdate" version="2.0.0">
    <name>heartbeat_{suffix}</name>
    <pv_name>pva://{heartbeat_pv}</pv_name>
    <x>330</x><y>{y}</y><width>100</width><height>20</height>
  </widget>
  <widget type="action_button" version="3.0.0">
    <name>restart_{suffix}</name>
    <actions>
      <action type="write_pv">
        <pv_name>pva://{restart_pv}</pv_name>
        <value>1</value>
        <description>Restart</description>
      </action>
    </actions>
    <text>restart</text>
    <x>440</x><y>{y}</y><width>80</width><height>20</height>
    <tooltip>Relaunch this instance (reinstalls from the source clone)</tooltip>
    <confirm_dialog>true</confirm_dialog>
    <confirm_message>Restart the PVA gateway on {ip}?</confirm_message>
  </widget>
"""

NOT_DEPLOYED_CELLS = """
  <widget type="label" version="2.0.0">
    <name>not_deployed_{suffix}</name>
    <text>not deployed</text>
    <x>170</x><y>{y}</y><width>350</width><height>20</height>
    <tooltip>No gateway instance installed on this host (absent from config.ini [pva] addr_list). Cameras: {cameras}</tooltip>
  </widget>
"""


def render(experiment: str, hosts: list[FleetHost]) -> str:
    """Return the ``.bob`` XML for *hosts*, one row each."""
    rows = []
    for i, host in enumerate(hosts):
        # Every DB/config string is XML-escaped; the XML comment carries no
        # names at all (a "--" inside a comment is a well-formedness error).
        fields = {
            "ip": escape(host.ip),
            "n_cameras": len(host.cameras),
            "cameras": escape(", ".join(host.cameras) or "no cameras in the DB"),
            # The same normalised host component the instance PVs use, so a
            # hostname entry gets a unique widget name too (not just IPv4).
            "suffix": normalize_component(host.ip),
            "y": FIRST_ROW_Y + i * ROW_HEIGHT,
            "version_pv": escape(host.instance_pv(experiment, "version")),
            "heartbeat_pv": escape(host.instance_pv(experiment, "heartbeat")),
            "restart_pv": escape(host.instance_pv(experiment, "restart")),
        }
        cells = DEPLOYED_CELLS if host.deployed else NOT_DEPLOYED_CELLS
        rows.append(HOST_LABEL.format(**fields) + cells.format(**fields))
    height = FIRST_ROW_Y + len(hosts) * ROW_HEIGHT + 20
    header = HEADER.format(
        height=height,
        experiment=escape(experiment),
        n_hosts=len(hosts),
        n_deployed=sum(h.deployed for h in hosts),
    )
    return header + "".join(rows) + "</display>\n"


def output_path(experiment: str, out_dir: Path | None = None) -> Path:
    """``fleet_status_<experiment>.bob`` next to this script (or in *out_dir*)."""
    name = f"fleet_status_{experiment.lower()}.bob"
    return (out_dir or Path(__file__).parent) / name


def main(argv: list[str] | None = None) -> int:
    """Write the fleet screen for one experiment."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--experiment",
        default=None,
        help="GEECS experiment (default: config.ini [Experiment])",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="client config.ini to read [pva] addr_list from (default: the user's)",
    )
    parser.add_argument(
        "--out-dir", type=Path, default=None, help="directory for the .bob"
    )
    args = parser.parse_args(argv)

    experiment = args.experiment or default_experiment(args.config)
    if not experiment:
        print(
            "no experiment: pass --experiment or set config.ini [Experiment]",
            file=sys.stderr,
        )
        return 2
    hosts = fleet_roster(experiment, config_path=args.config)
    if not hosts:
        print(
            f"no camera servers in the DB for experiment {experiment!r}",
            file=sys.stderr,
        )
        return 1
    path = output_path(experiment, args.out_dir)
    path.write_text(render(experiment, hosts), encoding="utf-8")
    n_dep = sum(h.deployed for h in hosts)
    print(
        f"wrote {path}: {len(hosts)} rows ({n_dep} deployed, {len(hosts) - n_dep} not deployed)"
    )
    for host in hosts:
        state = "deployed" if host.deployed else "NOT DEPLOYED"
        print(f"  {host.ip:<15} {state:<13} {len(host.cameras):>2} cameras")
    return 0


if __name__ == "__main__":
    sys.exit(main())
