"""Regenerate ``fleet_status.bob`` from the fleet host list below.

``HOSTS`` is the roster of record for the camera-server fleet: the endpoint
IPs that *should* run a GeecsPvaGateway instance, one screen row each. It
starts life as a snapshot of the experiment DB — enabled devices with
image-typed variables, grouped by endpoint IP — and is then curated by hand:
prune entries when a box is retired or confirmed deprecated (a roster entry
with no running instance shows as a permanently disconnected screen row).
The DB derivation uses :class:`geecs_pva_gateway.config.PvaGatewayConfig`
building blocks::

    endpoints = GeecsDb.get_experiment_devices("Undulator", enabled_only=True)
    var_map = GeecsDb.get_experiment_device_variables("Undulator", enabled_only=True)
    # keep ips whose devices have >=1 var with effective_vartype(...) == "image"

When the fleet changes: update ``HOSTS``, run this script (no arguments, no
network — plain ``python gen_fleet_status.py``), and commit both files.
"""

from pathlib import Path

EXPERIMENT = "Undulator"

# DB snapshot 2026-07-31: 13 endpoints, 49 cameras.
HOSTS = [
    "192.168.6.66",
    "192.168.6.73",
    "192.168.6.80",
    "192.168.6.100",
    "192.168.7.161",
    "192.168.7.162",
    "192.168.7.163",
    "192.168.7.164",
    "192.168.7.203",
    "192.168.8.197",
    "192.168.8.199",
    "192.168.8.201",
    "192.168.8.207",
]

ROW_HEIGHT = 30
FIRST_ROW_Y = 70

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Fleet health for GeecsPvaGateway instances: one row per camera server.
     GENERATED by gen_fleet_status.py (host roster + regeneration recipe in
     its docstring) - edit and rerun that script, do not hand-edit rows.
     Rollout = write 1 to :restart (confirmation dialog) - the service
     relaunches and reinstalls from the source clone; watch version converge.
     NOTE: this screen is itself a cross-subnet PVA client - Phoebus needs
     the full fleet address list (DEPLOYMENT.md "Client access") or rows on
     other subnets show disconnected. -->
<display version="2.0.0">
  <name>PVA Gateway Fleet</name>
  <width>640</width>
  <height>{height}</height>
  <widget type="label" version="2.0.0">
    <name>title</name>
    <text>GeecsPvaGateway fleet — {experiment}</text>
    <x>10</x><y>10</y><width>400</width><height>25</height>
    <font><font family="Liberation Sans" style="BOLD" size="16.0"></font></font>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_host</name>
    <text>host</text>
    <x>10</x><y>45</y><width>150</width><height>20</height>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_version</name>
    <text>version</text>
    <x>170</x><y>45</y><width>150</width><height>20</height>
  </widget>
  <widget type="label" version="2.0.0">
    <name>hdr_heartbeat</name>
    <text>heartbeat</text>
    <x>330</x><y>45</y><width>100</width><height>20</height>
  </widget>
"""

ROW = """
  <!-- row: {ip} -->
  <widget type="label" version="2.0.0">
    <name>host_{suffix}</name>
    <text>{ip}</text>
    <x>10</x><y>{y}</y><width>150</width><height>20</height>
  </widget>
  <widget type="textupdate" version="2.0.0">
    <name>version_{suffix}</name>
    <pv_name>pva://{prefix}:pvagateway:{token}:version</pv_name>
    <x>170</x><y>{y}</y><width>150</width><height>20</height>
  </widget>
  <widget type="textupdate" version="2.0.0">
    <name>heartbeat_{suffix}</name>
    <pv_name>pva://{prefix}:pvagateway:{token}:heartbeat</pv_name>
    <x>330</x><y>{y}</y><width>100</width><height>20</height>
  </widget>
  <widget type="action_button" version="3.0.0">
    <name>restart_{suffix}</name>
    <actions>
      <action type="write_pv">
        <pv_name>pva://{prefix}:pvagateway:{token}:restart</pv_name>
        <value>1</value>
        <description>Restart</description>
      </action>
    </actions>
    <text>restart</text>
    <x>440</x><y>{y}</y><width>80</width><height>20</height>
    <tooltip>Relaunch this instance (reinstalls from the source clone)</tooltip>
    <confirm_dialog>true</confirm_dialog>
    <confirm_message>Restart the PVA gateway on {ip}?</confirm_message>
  </widget>
"""


def main() -> None:
    """Write ``fleet_status.bob`` next to this script, one row per host."""
    prefix = EXPERIMENT.lower()
    rows = []
    for i, ip in enumerate(HOSTS):
        rows.append(
            ROW.format(
                ip=ip,
                token=ip.replace(".", "_"),
                # e.g. 6_100 — unique within one lab's 192.168.x.y fleet
                suffix="_".join(ip.split(".")[2:]),
                y=FIRST_ROW_Y + i * ROW_HEIGHT,
                prefix=prefix,
            )
        )
    height = FIRST_ROW_Y + len(HOSTS) * ROW_HEIGHT + 20
    out = (
        HEADER.format(height=height, experiment=EXPERIMENT)
        + "".join(rows)
        + "</display>\n"
    )
    path = Path(__file__).with_name("fleet_status.bob")
    path.write_text(out, encoding="utf-8")
    print(f"wrote {path}: {len(HOSTS)} rows, height {height}")


if __name__ == "__main__":
    main()
