---
name: example_single_camera_median
description: "Example using the geecs interface with the base geecs environment"
version: "0.1"
dependencies:
  - badger-opt
  - geecs_python_api
interface:
  - geecs