actions:
  close_gaia_internal_shutters:
    steps:
      - device: U_GaiaSVEReader
        variable: InternalShutterA
        action: set
        value: 1
      - device: U_GaiaSVEReader
        variable: InternalShutterB
        action: set
        value: 1
      - wait: 2
      - device: U_GaiaSVEReader
        variable: InternalShutterA
        action: get
        expected_value: 1
      - device: U_GaiaSVEReader
        variable: InternalShutterB
        action: get
        expected_value: 1

  insert_gaia_stops:
    steps:
      - device: U_148_PLC
        variable: DO.Ch1
        action: set
        value: 'on'
      - device: U_148_PLC
        variable: DO.Ch2
        action: set
        value: 'on'
      - wait: 1
      - device: U_148_PLC
        variable: DI.Ch1
        action: get
        expected_value: 'on'
      - device: U_148_PLC
        variable: DI.Ch3
        action: get
        expected_value: 'on'

  remove_gaia_stops:
    steps:
      - device: U_148_PLC
        variable: DO.Ch1
        action: set
        value: 'off'
      - device: U_148_PLC
        variable: DO.Ch2
        action: set
        value: 'off'
      - wait: 1
      - device: U_148_PLC
        variable: DI.Ch2
        action: get
        expected_value: 'on'
      - device: U_148_PLC
        variable: DI.Ch4
        action: get
        expected_value: 'on'

  insert_pmqs:
    steps:
      - action: execute
        action_name: insert_gaia_stops
      - device: U_Hexapod
        variable: ypos
        action: set
        value: -20

  remove_pmqs:
    steps:
      - action: execute
        action_name: insert_gaia_stops
      - device: U_Hexapod
        variable: ypos
        action: set
        value: -22
