composite_variables:
  ALine_e_beam_position_offset_x:
    components:
      - device: U_S3H
        variable: Current
        relation: "composite_var * 1"
      - device: U_S4H
        variable: Current
        relation: "composite_var * -1"

  ALine_e_beam_position_offset_y:
    components:
      - device: U_S3V
        variable: Current
        relation: "composite_var * 1"
      - device: U_S4V
        variable: Current
        relation: "composite_var * -1"

  ALine_e_beam_angle_offset_x:
    components:
      - device: U_S3H
        variable: Current
        relation: "composite_var * 1"
      - device: U_S4H
        variable: Current
        relation: "composite_var * -2"

  ALine_e_beam_angle_offset_y:
    components:
      - device: U_S3V
        variable: Current
        relation: "composite_var * 1"
      - device: U_S4V
        variable: Current
        relation: "composite_var * -2"

  R56_at_100MeV:
    components:
      - device: U_ChicaneInner
        variable: Current
        relation: "np.sqrt(100 ** 2 * composite_var / 560968.636)"
      - device: U_ChicaneOuter
        variable: Current
        relation: "-np.sqrt(100 ** 2 * composite_var / 560968.636)"    
