visa1: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 7'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam1"

visa2: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 6'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam2"

visa3: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 5'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam3"

visa4: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 4'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam4"

visa5: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 3'
  energy_meter_position: 3500
  spectrometer_position: 3500
  e-beam-camera: "UC_VisaEBeam5"

visa6: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 2'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam6"

visa7: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 1'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam7"

visa8: 
  device: 'U_VisaPlungers'
  variable: 'DigitalOutput.Channel 0'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam8"

visa9: 
  device: 'U_PLC'
  variable: 'DO.Ch19'
  energy_meter_position: 1
  spectrometer_position: 2
  e-beam-camera: "UC_VisaEBeam8"

