# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ScanDeviceOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 419)
        self.listScanVariables = QtWidgets.QListWidget(Dialog)
        self.listScanVariables.setGeometry(QtCore.QRect(10, 40, 251, 331))
        self.listScanVariables.setObjectName("listScanVariables")
        self.listCompositeVariables = QtWidgets.QListWidget(Dialog)
        self.listCompositeVariables.setGeometry(QtCore.QRect(310, 40, 251, 331))
        self.listCompositeVariables.setObjectName("listCompositeVariables")
        self.buttonMoveSooner = QtWidgets.QPushButton(Dialog)
        self.buttonMoveSooner.setGeometry(QtCore.QRect(270, 130, 31, 41))
        self.buttonMoveSooner.setObjectName("buttonMoveSooner")
        self.buttonMoveLater = QtWidgets.QPushButton(Dialog)
        self.buttonMoveLater.setGeometry(QtCore.QRect(270, 240, 31, 41))
        self.buttonMoveLater.setObjectName("buttonMoveLater")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 251, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.buttonSave = QtWidgets.QPushButton(Dialog)
        self.buttonSave.setGeometry(QtCore.QRect(160, 380, 93, 28))
        self.buttonSave.setObjectName("buttonSave")
        self.buttonClose = QtWidgets.QPushButton(Dialog)
        self.buttonClose.setGeometry(QtCore.QRect(320, 380, 93, 28))
        self.buttonClose.setObjectName("buttonClose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Scan Variable Ordering"))
        self.buttonMoveSooner.setText(_translate("Dialog", "↑"))
        self.buttonMoveLater.setText(_translate("Dialog", "↓"))
        self.label.setText(_translate("Dialog", "Scan Variables"))
        self.label_2.setText(_translate("Dialog", "Composite Variables"))
        self.buttonSave.setText(_translate("Dialog", "Save"))
        self.buttonClose.setText(_translate("Dialog", "Close"))
