"""Analysis-config schemas: the diagnostic document, the group document, and their parts.

Everything ImageAnalysis and ScanAnalysis load from ``scan_analysis_configs/``
is described here — pydantic only, so editors, the data portal, MCP and
CI can validate a diagnostic without the analysis stack installed.
"""

from geecs_schemas.analysis.canonical import canonical_document
from geecs_schemas.analysis.analyzers import (
    ANALYZER_SPECS,
    AnalyzerSpec,
    AnalyzerSpecBase,
    ArrayCalibrationSpec,
    BCaveMagOptSpec,
    BCaveMagSpecStitcherSpec,
    BeamAnalyzerSpec,
    CalibrationSpec,
    DnnAxisCalibrationSpec,
    DownrampPhaseSpec,
    FrogRetrievalSpec,
    FrogSpectralPhaseSpec,
    HasoAnalyzerSpec,
    HiResMagCamSpec,
    IctAnalyzerSpec,
    ImageKind,
    LineAnalyzerSpec,
    LineStitcherSpec,
    MagSpecAnalyzerSpec,
    PhaseDownrampSpec,
    PolynomialCalibrationSpec,
    PupilMask,
    StandardAnalyzerSpec,
    TraceAnalyzerSpec,
)
from geecs_schemas.analysis.diagnostic import (
    CURRENT_SCHEMA_VERSION,
    AnalysisDiagnostic,
    ImageSection,
)
from geecs_schemas.analysis.group import AnalysisGroup, AnalyzerRef
from geecs_schemas.analysis.processing_1d import (
    Data1DLoading,
    Data1DType,
    Line1DConfig,
    LineBackgroundConfig,
    LineBackgroundMethod,
    LineFilterMethod,
    LineFilteringConfig,
    LineInterpolationConfig,
    LinePipelineStepType,
    LineROIConfig,
    LineThresholdMethod,
    LineThresholdingConfig,
)
from geecs_schemas.analysis.processing_2d import (
    BackgroundConfig,
    BackgroundMethod,
    CameraConfig,
    CircularMaskConfig,
    CrosshairConfig,
    CrosshairMaskingConfig,
    FilteringConfig,
    NormalizationConfig,
    NormalizationMethod,
    ProcessingStepType,
    ROIConfig,
    ThresholdMethod,
    ThresholdMode,
    ThresholdingConfig,
    TransformConfig,
    VignetteConfig,
    VignetteMethod,
)
from geecs_schemas.analysis.renderer import RendererOptions
from geecs_schemas.analysis.scan_runtime import (
    AutodetectBackgroundSpec,
    BackgroundSource,
    FromCurrentScanSpec,
    ScanRuntime,
)

__all__ = [
    "ANALYZER_SPECS",
    "CURRENT_SCHEMA_VERSION",
    "AnalysisDiagnostic",
    "AnalysisGroup",
    "AnalyzerRef",
    "AnalyzerSpec",
    "AnalyzerSpecBase",
    "ArrayCalibrationSpec",
    "AutodetectBackgroundSpec",
    "BCaveMagOptSpec",
    "BCaveMagSpecStitcherSpec",
    "BackgroundConfig",
    "BackgroundMethod",
    "BackgroundSource",
    "BeamAnalyzerSpec",
    "CalibrationSpec",
    "CameraConfig",
    "CircularMaskConfig",
    "CrosshairConfig",
    "CrosshairMaskingConfig",
    "Data1DLoading",
    "Data1DType",
    "DnnAxisCalibrationSpec",
    "DownrampPhaseSpec",
    "FilteringConfig",
    "FrogRetrievalSpec",
    "FrogSpectralPhaseSpec",
    "FromCurrentScanSpec",
    "HasoAnalyzerSpec",
    "HiResMagCamSpec",
    "IctAnalyzerSpec",
    "ImageKind",
    "ImageSection",
    "Line1DConfig",
    "LineAnalyzerSpec",
    "LineBackgroundConfig",
    "LineBackgroundMethod",
    "LineFilterMethod",
    "LineFilteringConfig",
    "LineInterpolationConfig",
    "LinePipelineStepType",
    "LineROIConfig",
    "LineStitcherSpec",
    "LineThresholdMethod",
    "LineThresholdingConfig",
    "MagSpecAnalyzerSpec",
    "NormalizationConfig",
    "NormalizationMethod",
    "PhaseDownrampSpec",
    "PolynomialCalibrationSpec",
    "ProcessingStepType",
    "PupilMask",
    "ROIConfig",
    "RendererOptions",
    "ScanRuntime",
    "StandardAnalyzerSpec",
    "ThresholdMethod",
    "ThresholdMode",
    "ThresholdingConfig",
    "TraceAnalyzerSpec",
    "TransformConfig",
    "VignetteConfig",
    "VignetteMethod",
    "canonical_document",
]
