visa1:
  yag_screen: True
  center_yx: [350, 1200]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: 'NA'
    wavelength: 'NA'

visa2:
  yag_screen: True
  center_yx: [880, 1100]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: 'NA'
    wavelength: 'NA'

visa3:
  yag_screen: True
  center_yx: [1450, 1150]
  incoherent_fit: [35.33062492, -992.32697961]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/06/2025'
    wavelength: 'NA'

visa4:
  yag_screen: True
  center_yx: [1000, 1200]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: 'NA'
    wavelength: 'NA'

visa5:
  yag_screen: True
  center_yx: [1120, 1375]
  incoherent_fit: [21.59520165, -522.88134454]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/06/2025'
    wavelength: 'NA'

visa6:
  yag_screen: True
  center_yx: [570, 1200]
  incoherent_fit: [513.55988929, 20909.08308676]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/06/2025'
    wavelength: 'NA'

visa7:
  yag_screen: True
  center_yx: [1490, 1120]
  incoherent_fit: [18.41720438, -406.04654234]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/06/2025'
    wavelength: 'NA'

visa9:
  yag_screen: False
  center_yx: [1500, 1300]
  incoherent_fit: [3625.27726207, -77730.79509378]
  zeroth_order: 273.2
  wavelength_per_pixel: 0.39883
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/18/2025'
    wavelength: '03/04/2025'
