visa4:
  yag_screen: True
  center_yx: [1000, 1750]
  calibration_dates:
    crop_region: '02/13/2025'
    incoherent: 'NA'
    wavelength: 'NA'

visa5:
  yag_screen: True
  center_yx: [1100, 1800]
  calibration_dates:
    crop_region: '02/13/2025'
    incoherent: 'NA'
    wavelength: 'NA'

visa9:
  yag_screen: False
  center_yx: [1500, 1300]
  incoherent_fit: [1625.01620916, -37119.80952916]
  calibration_dates:
    crop_region: '03/06/2025'
    incoherent: '03/06/2025'
    wavelength: 'NA'
