controls_file: beamlineIn.txt
objective_targets:
  var1:
    device_name: UC_Amp2_IR_input
    device_subscribe_variables:
      - MeanCounts
      - MaxCounts
  var2:
    device_name: UC_Amp3_IR_input
    device_subscribe_variables:
      - MeanCounts
generator:
  name: 
optimization_steps: 21
shots_per_step: 5
disable_sets: False
function_name: test_function