# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 276)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(70, 150, 93, 28))
        self.buttonStart.setObjectName("buttonStart")
        self.buttonStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStop.setGeometry(QtCore.QRect(70, 190, 93, 28))
        self.buttonStop.setObjectName("buttonStop")
        self.inputYear = QtWidgets.QLineEdit(self.centralwidget)
        self.inputYear.setGeometry(QtCore.QRect(90, 40, 113, 22))
        self.inputYear.setObjectName("inputYear")
        self.inputMonth = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMonth.setGeometry(QtCore.QRect(90, 70, 113, 22))
        self.inputMonth.setObjectName("inputMonth")
        self.inputDay = QtWidgets.QLineEdit(self.centralwidget)
        self.inputDay.setGeometry(QtCore.QRect(90, 100, 113, 22))
        self.inputDay.setObjectName("inputDay")
        self.labelYear = QtWidgets.QLabel(self.centralwidget)
        self.labelYear.setGeometry(QtCore.QRect(30, 40, 55, 16))
        self.labelYear.setObjectName("labelYear")
        self.labelMonth = QtWidgets.QLabel(self.centralwidget)
        self.labelMonth.setGeometry(QtCore.QRect(30, 70, 55, 16))
        self.labelMonth.setObjectName("labelMonth")
        self.labelDay = QtWidgets.QLabel(self.centralwidget)
        self.labelDay.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.labelDay.setObjectName("labelDay")
        self.outputLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputLog.setGeometry(QtCore.QRect(240, 40, 631, 192))
        self.outputLog.setObjectName("outputLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.labelYear.setText(_translate("MainWindow", "Year"))
        self.labelMonth.setText(_translate("MainWindow", "Month"))
        self.labelDay.setText(_translate("MainWindow", "Day"))
