name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on changed files
        run: |
          FROM_REF="${{ github.event.pull_request.base.sha }}"
          if [ -z "$FROM_REF" ]; then
            FROM_REF="${{ github.event.before }}"
          fi
          pre-commit run --from-ref "$FROM_REF" --to-ref "${{ github.sha }}" --show-diff-on-failure --color always
